bold:
    name: profiles_buttons_bold
    key: B
    className: bold
    closeWith:
        textile: "*"
    openWith:
        textile: "*"

code:
    name: profiles_buttons_code
    className: code
    closeWith:
        textile: "@"
    openWith:
        textile: "@"

clips:
    name: profiles_buttons_clips
    className: clips

deleted:
    name: profiles_buttons_deleted
    key: S
    className: deleted
    closeWith:
        textile: "-"
    openWith:
        textile: "-"

heading1:
    name: profiles_buttons_heading1
    className: heading1
    openWith:
        textile: '\n\nh1. '
    closeWith:
        textile: '\n\n'

heading2:
    name: profiles_buttons_heading2
    className: heading2
    openWith:
        textile: '\n\nh2. '
    closeWith:
        textile: '\n\n'

heading3:
    name: profiles_buttons_heading3
    className: heading3
    openWith:
        textile: '\n\nh3. '
    closeWith:
        textile: '\n\n'

heading4:
    name: profiles_buttons_heading4
    className: heading4
    openWith:
        textile: '\n\nh4. '
    closeWith:
        textile: '\n\n'

heading5:
    name: profiles_buttons_heading5
    className: heading5
    openWith:
        textile: '\n\nh5. '
    closeWith:
        textile: '\n\n'

heading6:
    name: profiles_buttons_heading6
    className: heading6
    openWith:
        textile: '\n\nh6. '
    closeWith:
        textile: '\n\n'

image:
    name: profiles_buttons_image
    className: image
    replaceWith:
        textile: "function(h) {return btnImageCallback(h);}"

italic:
    name: profiles_buttons_italic
    key: I
    className: italic
    closeWith:
        textile: "_"
    openWith:
        textile: "_"

link:
    name: profiles_buttons_link
    className: link
    children:
        internal:
            name: profiles_buttons_link_option_internal
            replaceWith:
                textile: "function(h) {return btnLinkInternalCallback(h);}"
        external:
            name: profiles_buttons_link_option_external
            replaceWith:
                textile: "function(h) {return btnLinkExternalCallback(h);}"
        mailto:
            name: profiles_buttons_link_option_mailto
            replaceWith:
                textile: "function(h) {return btnLinkMailtoCallback(h);}"

orderedlist:
    name: profiles_buttons_orderedlist
    className: orderedlist
    replaceWith:
        textile: "function(h) {return btnOrderedlistCallback(h);}"

paragraph:
    name: profiles_buttons_paragraph
    className: paragraph
    openWith:
        textile: "p. "

quote:
    name: profiles_buttons_quote
    className: quote
    closeWith:
        textile: ""
    openWith:
        textile: "bq. "

sub:
    name: profiles_buttons_sub
    className: sub
    closeWith:
        textile: "~"
    openWith:
        textile: "~"

sup:
    name: profiles_buttons_sup
    className: sup
    closeWith:
        textile: "^"
    openWith:
        textile: "^"

table:
    name: profiles_buttons_table
    className: table
    replaceWith:
        textile: "function(h) {return btnTableCallback(h);}"

underline:
    name: profiles_buttons_underline
    key: U
    className: underline
    closeWith:
        textile: "+"
    openWith:
        textile: "+"

unorderedlist:
    name: profiles_buttons_unorderedlist
    className: unorderedlist
    replaceWith:
        textile: "function(h) {return btnUnorderedlistCallback(h);}"